/** Auto-generated by web/scripts/generate-marker-deep-reads.mjs — do not edit by hand. */

import type { MarkerDeepRead } from './markerDeepReadsTypes';

export const MARKER_DEEP_READS_AUTO: Record<string, MarkerDeepRead> = {
  "a-lost-world": {
    href: "/information/a-lost-world/",
    title: "A Lost World — full narrative",
    description: "\"A Lost World\" by John Muir",
  },
  "a-soul-searching-birthday": {
    href: "/information/a-soul-searching-birthday/",
    title: "A Soul-Searching Birthday — full narrative",
    description: "A Soul-Searching Birthday",
  },
  "a-trail-through-history-when-montanas-roads-had-names": {
    href: "/information/a-trail-through-history-when-montanas-roads-had-names/",
    title: "A Trail Through History / When Montana's Roads Had Names — full narrative",
    description: "A Trail Through History / When Montana's Roads Had Names",
  },
  "a-wonderful-piece-of-engineering-the-mullan-road": {
    href: "/information/a-wonderful-piece-of-engineering-the-mullan-road/",
    title: "A wonderful Piece of Engineering: The Mullan Road — full narrative",
    description: "A wonderful Piece of Engineering: The Mullan Road",
  },
  "big-arm-school": {
    href: "/information/big-arm-school/",
    title: "Big Arm School — full narrative",
    description: "Big Arm School",
  },
  "big-horn-sheep-conservation": {
    href: "/information/big-horn-sheep-conservation/",
    title: "Big Horn Sheep Conservation — full narrative",
    description: "Big Horn Sheep Conservation",
  },
  "brave-new-world": {
    href: "/information/brave-new-world/",
    title: "Brave New World — full narrative",
    description: "Brave New World",
  },
  "cycles-and-circles": {
    href: "/information/cycles-and-circles/",
    title: "Cycles and Circles — full narrative",
    description: "Companion narrative for the historic marker: Cycles and Circles.",
  },
  "danger-ahead": {
    href: "/information/danger-ahead/",
    title: "Danger Ahead! — full narrative",
    description: "Danger Ahead!",
  },
  "fort-fizzle": {
    href: "/information/fort-fizzle/",
    title: "Fort Fizzle — full narrative",
    description: "Fort Fizzle",
  },
  "fort-thompson-playground": {
    href: "/information/fort-thompson-playground/",
    title: "Fort Thompson Playground — full narrative",
    description: "Fort Thompson Playground",
  },
  "glacial-lake-missoula": {
    href: "/information/glacial-lake-missoula/",
    title: "Glacial Lake Missoula — full narrative",
    description: "Glacial Lake Missoula",
  },
  "glacial-lake-missoula-3": {
    href: "/information/glacial-lake-missoula/",
    title: "Glacial Lake Missoula — full narrative",
    description: "Glacial Lake Missoula",
  },
  "hepburns-mesa": {
    href: "/information/hepburns-mesa/",
    title: "Hepburn's Mesa — full narrative",
    description: "Hepburn's Mesa",
  },
  "it-was-mutually-advantageous": {
    href: "/information/it-was-mutually-advantageous/",
    title: "\"it was mutually advantageous...\" — full narrative",
    description: "\"it was mutually advantageous...\"",
  },
  "join-the-voyage-of-discovery": {
    href: "/information/join-the-voyage-of-discovery/",
    title: "Join the Voyage of Discovery — full narrative",
    description: "Join the Voyage of Discovery",
  },
  "join-the-voyage-of-discovery-2": {
    href: "/information/join-the-voyage-of-discovery/",
    title: "Join the Voyage of Discovery — full narrative",
    description: "Join the Voyage of Discovery",
  },
  "join-the-voyage-of-discovery-3": {
    href: "/information/join-the-voyage-of-discovery/",
    title: "Join the Voyage of Discovery — full narrative",
    description: "Join the Voyage of Discovery",
  },
  "join-the-voyage-of-discovery-4": {
    href: "/information/join-the-voyage-of-discovery/",
    title: "Join the Voyage of Discovery — full narrative",
    description: "Join the Voyage of Discovery",
  },
  "join-the-voyage-of-discovery-5": {
    href: "/information/join-the-voyage-of-discovery/",
    title: "Join the Voyage of Discovery — full narrative",
    description: "Join the Voyage of Discovery",
  },
  "join-the-voyage-of-discovery-6": {
    href: "/information/join-the-voyage-of-discovery/",
    title: "Join the Voyage of Discovery — full narrative",
    description: "Join the Voyage of Discovery",
  },
  "join-the-voyage-of-discovery-7": {
    href: "/information/join-the-voyage-of-discovery/",
    title: "Join the Voyage of Discovery — full narrative",
    description: "Join the Voyage of Discovery",
  },
  "join-the-voyage-of-discovery-8": {
    href: "/information/join-the-voyage-of-discovery/",
    title: "Join the Voyage of Discovery — full narrative",
    description: "Join the Voyage of Discovery",
  },
  "journey-through-the-blackfoot": {
    href: "/information/journey-through-the-blackfoot/",
    title: "Journey Through the Blackfoot — full narrative",
    description: "Journey Through the Blackfoot",
  },
  "kootenai-falls-people-and-history": {
    href: "/information/kootenai-falls-people-and-history/",
    title: "Kootenai Falls People and History — full narrative",
    description: "Kootenai Falls People and History",
  },
  "lewis-and-clark-at-ross-hole": {
    href: "/information/lewis-and-clark-at-ross-hole/",
    title: "Lewis and Clark at Ross' Hole — full narrative",
    description: "Lewis and Clark at Ross' Hole",
  },
  "lewis-and-clark-in-salish-territory": {
    href: "/information/lewis-and-clark-in-salish-territory-123385/",
    title: "Lewis and Clark in Salish Territory — full narrative",
    description: "The Corps of Discovery's crucial encounters with the Salish people at Tmsmli, the Place of No Salmon, before their brutal crossing of the Bitterroot Mountains.",
  },
  "lewis-and-clark-on-lolo-creek": {
    href: "/information/lewis-and-clark-on-lolo-creek/",
    title: "Lewis and Clark on Lolo Creek — full narrative",
    description: "Lewis and Clark on Lolo Creek",
  },
  "motoring-through-paradise-the-vigilante-trail": {
    href: "/information/motoring-through-paradise-the-vigilante-trail/",
    title: "Motoring Through Paradise: The Vigilante Trail — full narrative",
    description: "Motoring Through Paradise: The Vigilante Trail",
  },
  "mountain-bighorn-sheep": {
    href: "/information/mountain-bighorn-sheep/",
    title: "Mountain (Bighorn) Sheep — full narrative",
    description: "Mountain (Bighorn) Sheep",
  },
  "nez-perce-camp": {
    href: "/information/nez-perce-camp/",
    title: "Nez Perce Camp — full narrative",
    description: "Nez Perce Camp",
  },
  "road-to-the-buffalo": {
    href: "/information/road-to-the-buffalo/",
    title: "Road to the Buffalo — full narrative",
    description: "Road to the Buffalo",
  },
  "road-to-the-buffalo-2": {
    href: "/information/road-to-the-buffalo/",
    title: "Road to the Buffalo — full narrative",
    description: "Road to the Buffalo",
  },
  "salmon-river-scenic-byway": {
    href: "/information/salmon-river-scenic-byway/",
    title: "Salmon River Scenic Byway — full narrative",
    description: "Salmon River Scenic Byway",
  },
  "the-blackfoot-river-corridor": {
    href: "/information/the-blackfoot-river-corridor/",
    title: "The Blackfoot River Corridor — full narrative",
    description: "The Blackfoot River Corridor",
  },
  "the-bozeman-trail-4": {
    href: "/information/the-bozeman-trail/",
    title: "The Bozeman Trail — full narrative",
    description: "The Bozeman Trail",
  },
  "the-bruck": {
    href: "/information/the-bruck/",
    title: "The Bruck\" was a machine built for purpose, a testament to the ingenuity that tamed the vast American West. You would have seen it, perhaps, a distinctive orange and green leviathan, plying the roads between Whitefish and Kalispell, a vital link in the Great Northern Railway's intricate network. It was not a thing of beauty in the classical sense, but a thing of function, and in that function, it found its own rugged elegance. For those who understood the logistics of moving men and materiel across a challenging landscape, the Bruck was a marvel of engineering, a solution to a problem that had vexed the railway for years. It was, as one railway man put it, a workhorse. — full narrative",
    description: "\"The Bruck\" was a machine built for purpose, a testament to the ingenuity that tamed the vast American West. You would have seen it, perhaps, a distinctive orange and green leviathan, plying the ro…",
  },
  "the-lolo-trail": {
    href: "/information/the-lolo-trail/",
    title: "The Lolo Trail — full narrative",
    description: "The Lolo Trail",
  },
  "the-nez-perce-sikum": {
    href: "/information/the-nez-perce-sikum/",
    title: "The Nez Perce Sikum — full narrative",
    description: "The Nez Perce Sikum",
  },
  "the-northern-pacific-railways-last-spike-celebration": {
    href: "/information/the-northern-pacific-railways-last-spike-celebration/",
    title: "The Northern Pacific Railway's Last Spike Celebration — full narrative",
    description: "The Northern Pacific Railway's Last Spike Celebration",
  },
  "the-summer-of-1877": {
    href: "/information/the-summer-of-1877/",
    title: "The Summer of 1877 — full narrative",
    description: "The Summer of 1877",
  },
  "the-time-when-the-people-fought-the-soldiers": {
    href: "/information/the-time-when-the-people-fought-the-soldiers/",
    title: "The Time When The People Fought The Soldiers. — full narrative",
    description: "The Time When The People Fought The Soldiers.",
  },
  "the-way-they-saw-it": {
    href: "/information/the-way-they-saw-it/",
    title: "The Way They Saw It — full narrative",
    description: "The Way They Saw It",
  },
  "this-springblubbers-with-heat": {
    href: "/information/this-springblubbers-with-heat/",
    title: "\"this spring...blubbers with heat\" — full narrative",
    description: "\"this spring...blubbers with heat\"",
  },
  "trail-through-time": {
    href: "/information/trail-through-time/",
    title: "Trail Through Time — full narrative",
    description: "Trail Through Time",
  },
  "travelers-crossroads-for-centuries": {
    href: "/information/travelers-crossroads-for-centuries/",
    title: "Traveler's Crossroads for Centuries — full narrative",
    description: "Traveler's Crossroads for Centuries",
  },
  "which-way-did-lewis-clark-go": {
    href: "/information/which-way-did-lewis-clark-go/",
    title: "Which Way Did Lewis & Clark Go? — full narrative",
    description: "Which Way Did Lewis & Clark Go?",
  },
};
