# Netlify configuration file

[build]
  # Build from the Next.js app and publish the static export
  base = "web"
  publish = "out"
  command = "npm install && npm run build"
  # Netlify will use /404.html from the publish directory automatically

# Redirects and headers

# Pretty URLs
[[redirects]]
  from = "/*.html"
  to = "/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Enable asset optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
