# Netlify configuration file

[build]
  publish = "/"
  command = "# no build command needed for static HTML site"

# Redirects and headers
[[redirects]]
  from = "/*.html"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom 404 handling
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/404.html"
  to = "/404.html"
  status = 404


[build.environment]
  NODE_VERSION = "16"

# Enable asset optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
