# Netlify configuration file

[build]
  publish = "/"
  command = "# no build command needed for static HTML site"
  # This is the key part - tell Netlify which page to use for 404s
  not_found = "/404.html"

# Redirects and headers

# Pretty URLs
[[redirects]]
  from = "/*.html"
  to = "/:splat"
  status = 200

# Default catch-all is only for existing pages to be routed to index.html (SPA behavior)
# This won't interfere with 404 handling for non-existent files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[build.environment]
  NODE_VERSION = "16"

# Enable asset optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
