/*
 * Generate sitemap index and individual sitemaps into out/ after next export.
 *
 * IMPORTANT — local vs deployed sitemaps:
 *   This script runs as part of `npm run build` (after `next export`).
 *   It writes split sitemaps (sitemap-core.xml, sitemap-towns.xml, …)
 *   and a sitemap index (sitemap.xml) into web/out/.
 *
 *   On Netlify, the build runs fresh and out/ is the deploy directory,
 *   so the LIVE sitemap is always generated by this script.
 *
 *   Locally, web/out/ is gitignored and may be stale or missing.
 *   DO NOT treat local web/out/sitemap.xml as the source of truth.
 *   To inspect the live sitemap, fetch https://treasurestate.com/sitemap.xml
 *   or run `npm run build` locally to regenerate.
 *
 *   The file web/public/sitemap.xml is a LEGACY PLACEHOLDER from May 2025.
 *   Next.js copies public/ into out/ before this script runs, but this
 *   script overwrites it. The public/ copy is never deployed.
 */
const fs = require('fs');
const path = require('path');

const baseUrl = process.env.SITE_URL || 'https://treasurestate.com';

function getTownList(repoRoot) {
  const listPath = path.join(repoRoot, 'cities_towns_list', 'towns.txt');
  if (!fs.existsSync(listPath)) return [];
  const seen = new Set();
  return fs
    .readFileSync(listPath, 'utf8')
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean)
    .map((name) => ({ name, slug: name.toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-').replace(/-+/g, '-') }))
    .filter((t) => { if (seen.has(t.slug)) return false; seen.add(t.slug); return true; });
}

function getLastmod(loc) {
  if (loc.includes('/this-day-in-history/')) return '2026-04-14';
  if (loc.includes('/lodging/') && !loc.endsWith('/lodging/')) return '2026-03-14';
  if (loc.includes('/events/')) return '2026-03-21';
  if (loc.includes('/historic-markers/')) return '2026-03-29';
  if (loc.includes('/ghost-towns/')) return '2026-04-18';
  if (loc.includes('/history-trails/')) return '2026-03-29';
  if (loc.includes('/montana-railroad-history/')) return '2026-04-11';
  if (/\/guides\/moving-to-/.test(loc)) return '2026-03-01';
  if (loc.includes('/montana-towns/')) return '2026-03-01';
  if (loc.includes('/compare/')) return '2026-03-01';
  if (loc.includes('/best-of/')) return '2026-02-01';
  if (loc.includes('/information/')) return '2026-03-14';
  if (loc.includes('/guides/')) return '2026-03-01';
  if (loc.includes('/planners/')) return '2026-03-01';
  return '2026-01-01';
}

function getPriority(loc) {
  if (loc === baseUrl + '/') return 1.0;
  if (loc === baseUrl + '/montana-towns/') return 0.9;
  if (loc === baseUrl + '/this-day-in-history/') return 0.8;
  if (loc === baseUrl + '/this-day-in-history/browse/') return 0.7;
  if (/\/this-day-in-history\/[^/]+\/\d+\/$/.test(loc)) return 0.65;
  if (/\/montana-towns\/[^/]+\/$/.test(loc)) return 0.9;
  if (/\/guides\/moving-to-/.test(loc)) return 0.8;
  if (/\/lodging\/[^/]+\//.test(loc)) return 0.8;
  if (loc === baseUrl + '/lodging/') return 0.75;
  if (loc === baseUrl + '/events/') return 0.75;
  if (loc === baseUrl + '/historic-markers/') return 0.75;
  if (loc === baseUrl + '/guides/history-trails/') return 0.75;
  if (loc === baseUrl + '/guides/montana-railroad-history/') return 0.75;
  if (/\/montana-railroad-history\/[^/]+\//.test(loc)) return 0.7;
  if (/\/history-trails\/[^/]+\//.test(loc)) return 0.7;
  if (/\/historic-markers\/[^/]+\//.test(loc)) return 0.6;
  if (loc === baseUrl + '/ghost-towns/') return 0.75;
  if (loc === baseUrl + '/ghost-towns/all/') return 0.72;
  if (/\/ghost-towns\/[^/]+\//.test(loc)) return 0.65;
  if (/\/montana-towns\/[^/]+\/[^/]+\//.test(loc)) return 0.7;
  if (/\/guides\//.test(loc)) return 0.7;
  if (/\/best-of\//.test(loc)) return 0.7;
  if (/\/planners\//.test(loc)) return 0.7;
  if (/\/information\//.test(loc)) return 0.6;
  if (/\/compare\//.test(loc)) return 0.5;
  return 0.6;
}

function urlEntry(loc, changefreq = 'monthly') {
  const lastmod = getLastmod(loc);
  const priority = getPriority(loc);
  return `  <url>\n    <loc>${loc}</loc>\n    <lastmod>${lastmod}</lastmod>\n    <changefreq>${changefreq}</changefreq>\n    <priority>${priority}</priority>\n  </url>`;
}

function writeSitemap(outDir, filename, entries) {
  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries.join('\n')}\n</urlset>\n`;
  fs.writeFileSync(path.join(outDir, filename), xml, 'utf8');
  return entries.length;
}

function writeSitemapIndex(outDir, sitemaps, today) {
  const entries = sitemaps.map(name => 
    `  <sitemap>\n    <loc>${baseUrl}/${name}</loc>\n    <lastmod>${today}</lastmod>\n  </sitemap>`
  );
  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries.join('\n')}\n</sitemapindex>\n`;
  fs.writeFileSync(path.join(outDir, 'sitemap.xml'), xml, 'utf8');
}

(function main() {
  const webDir = path.resolve(__dirname, '..');
  const outDir = path.join(webDir, 'out');
  const repoRoot = path.resolve(__dirname, '..', '..');
  const today = new Date().toISOString().split('T')[0];

  if (!fs.existsSync(outDir)) {
    console.log('out/ directory does not exist, sitemap generation skipped.');
    return;
  }

  const towns = getTownList(repoRoot);
  const sitemaps = [];
  const stats = {};

  // Helper to collect URLs
  function collectUrls(name, collector) {
    const seen = new Set();
    const entries = [];
    const add = (loc, changefreq = 'monthly') => {
      if (seen.has(loc)) return;
      seen.add(loc);
      entries.push(urlEntry(loc, changefreq));
    };
    collector(add);
    if (entries.length > 0) {
      const filename = `sitemap-${name}.xml`;
      stats[name] = writeSitemap(outDir, filename, entries);
      sitemaps.push(filename);
    }
  }

  // ═══ 1. CORE PAGES (homepage, hubs, key landing pages) ═══
  collectUrls('core', (add) => {
    add(`${baseUrl}/`, 'weekly');
    add(`${baseUrl}/montana-towns/`, 'weekly');
    add(`${baseUrl}/guides/`);
    add(`${baseUrl}/lodging/`);
    add(`${baseUrl}/events/`, 'monthly');
    add(`${baseUrl}/compare/`);
    add(`${baseUrl}/planners/`);
    add(`${baseUrl}/nearby/`, 'weekly');
    add(`${baseUrl}/best-of/`);
    add(`${baseUrl}/gear/`);
    add(`${baseUrl}/this-day-in-history/`, 'weekly');
  });

  // ═══ 1b. THIS DAY IN HISTORY ═══
  collectUrls('tdih', (add) => {
    add(`${baseUrl}/this-day-in-history/browse/`);
    const tdihPath = path.join(repoRoot, 'docs', 'TDIH', 'montana_tdih_dataset', 'montana_tdih.json');
    if (fs.existsSync(tdihPath)) {
      const tdih = JSON.parse(fs.readFileSync(tdihPath, 'utf8'));
      const monthSlugs = [
        'january', 'february', 'march', 'april', 'may', 'june',
        'july', 'august', 'september', 'october', 'november', 'december',
      ];
      for (const entry of tdih) {
        const monthSlug = monthSlugs[entry.month - 1];
        add(`${baseUrl}/this-day-in-history/${monthSlug}/${entry.day}/`);
      }
    }
  });

  // ═══ 2. INFORMATION (Montana Facts articles) ═══
  collectUrls('information', (add) => {
    const infoDir = fs.existsSync(path.join(outDir, 'information'))
      ? path.join(outDir, 'information')
      : path.join(outDir, 'Information');
    if (fs.existsSync(infoDir)) {
      for (const f of fs.readdirSync(infoDir)) {
        if (f === 'js') continue;
        const full = path.join(infoDir, f);
        const isPage = f.endsWith('.html') ||
          (fs.statSync(full).isDirectory() && fs.existsSync(path.join(full, 'index.html')));
        if (isPage) {
          const slug = f.replace('.html', '');
          add(`${baseUrl}/information/${slug}/`);
        }
      }
    }
  });

  // ═══ 3. GUIDES (activity guides, moving guides) ═══
  collectUrls('guides', (add) => {
    // Manually add key guides first
    const keyGuides = [
      'montana-backroads', 'fly-fishing-guide', 'fly-fishing-rivers', 'hot-springs-guide',
      'golf-courses-guide', 'campgrounds-guide', 'hiking-guide', 'hunting-guide', 'land-ownership', 'skiing-guide', 'state-parks-guide',
      'wildlife-guide', 'photography-guide', 'summer-road-trips', 'winter-driving-guide', 'bitterroot-valley'
    ];
    for (const g of keyGuides) {
      add(`${baseUrl}/guides/${g}/`);
    }
    // Add any other guides from output
    const guidesDir = path.join(outDir, 'guides');
    if (fs.existsSync(guidesDir)) {
      for (const f of fs.readdirSync(guidesDir)) {
        if (fs.statSync(path.join(guidesDir, f)).isDirectory()) {
          add(`${baseUrl}/guides/${f}/`);
        }
      }
    }
  });

  // ═══ 3b. HISTORY TRAILS ═══
  collectUrls('history-trails', (add) => {
    add(`${baseUrl}/guides/history-trails/`);
    const trailsPath = path.join(webDir, 'data', 'history-trails.json');
    if (fs.existsSync(trailsPath)) {
      const trails = JSON.parse(fs.readFileSync(trailsPath, 'utf8'));
      for (const t of trails) {
        add(`${baseUrl}/guides/history-trails/${t.id}/`);
      }
    }
  });

  // ═══ 3c. RAILROAD HISTORY ═══
  collectUrls('railroad-history', (add) => {
    add(`${baseUrl}/guides/montana-railroad-history/`);
    const railroadPath = path.join(webDir, 'data', 'railroad-history.json');
    if (fs.existsSync(railroadPath)) {
      const railroadData = JSON.parse(fs.readFileSync(railroadPath, 'utf8'));
      for (const article of railroadData.articles) {
        add(`${baseUrl}/guides/montana-railroad-history/${article.slug}/`);
      }
    }
  });

  // ═══ 3d. HISTORIC MARKERS (curated only) ═══
  collectUrls('historic-markers', (add) => {
    add(`${baseUrl}/historic-markers/`);
    const curatedPath = path.join(webDir, 'data', 'historic-markers-curated.json');
    if (fs.existsSync(curatedPath)) {
      const markers = JSON.parse(fs.readFileSync(curatedPath, 'utf8'));
      for (const m of markers) {
        add(`${baseUrl}/historic-markers/${m.slug}/`);
      }
    }
  });

  // ═══ 3e. GHOST TOWNS (hub, GNIS index, curated articles) ═══
  collectUrls('ghost-towns', (add) => {
    add(`${baseUrl}/ghost-towns/`, 'weekly');
    add(`${baseUrl}/ghost-towns/all/`, 'monthly');
    const detailPath = path.join(webDir, 'data', 'ghost-towns-detail.json');
    if (fs.existsSync(detailPath)) {
      const rows = JSON.parse(fs.readFileSync(detailPath, 'utf8'));
      for (const row of rows) {
        if (row.slug) add(`${baseUrl}/ghost-towns/${row.slug}/`);
      }
    }
  });

  // ═══ 4. PLANNERS ═══
  collectUrls('planners', (add) => {
    add(`${baseUrl}/planners/backroads-planner/`, 'weekly');
    const corridorsPath = path.join(webDir, 'data', 'corridors.json');
    if (fs.existsSync(corridorsPath)) {
      const corridors = JSON.parse(fs.readFileSync(corridorsPath, 'utf8'));
      for (const c of corridors) {
        add(`${baseUrl}/planners/corridors/${c.id}/`);
      }
    }
  });

  // ═══ 5. LODGING (town lodging pages) ═══
  collectUrls('lodging', (add) => {
    const lodgingDir = path.join(outDir, 'lodging');
    if (fs.existsSync(lodgingDir)) {
      for (const f of fs.readdirSync(lodgingDir)) {
        const full = path.join(lodgingDir, f);
        if (fs.statSync(full).isDirectory()) {
          add(`${baseUrl}/lodging/${f}/`);
        }
      }
    }
  });

  // ═══ 6. TOWNS (main town pages) ═══
  collectUrls('towns', (add) => {
    for (const t of towns) {
      const townOutDir = path.join(outDir, 'montana-towns', t.slug);
      const hasTopics = fs.existsSync(townOutDir) &&
        fs.readdirSync(townOutDir).some((sub) => {
          const subPath = path.join(townOutDir, sub);
          return fs.statSync(subPath).isDirectory() && fs.existsSync(path.join(subPath, 'index.html'));
        });
      add(`${baseUrl}/montana-towns/${t.slug}/`, hasTopics ? 'weekly' : 'monthly');
    }
  });

  // ═══ 7. TOWN TOPICS (sub-pages: things-to-do, history, etc.) ═══
  collectUrls('town-topics', (add) => {
    for (const t of towns) {
      const townOutDir = path.join(outDir, 'montana-towns', t.slug);
      if (fs.existsSync(townOutDir)) {
        for (const sub of fs.readdirSync(townOutDir)) {
          const subPath = path.join(townOutDir, sub);
          if (fs.statSync(subPath).isDirectory() && fs.existsSync(path.join(subPath, 'index.html'))) {
            add(`${baseUrl}/montana-towns/${t.slug}/${sub}/`);
          }
        }
      }
    }
  });

  // ═══ 8. BEST-OF (rankings) ═══
  collectUrls('best-of', (add) => {
    const bestOfDir = path.join(outDir, 'best-of');
    if (fs.existsSync(bestOfDir)) {
      for (const f of fs.readdirSync(bestOfDir)) {
        if (fs.statSync(path.join(bestOfDir, f)).isDirectory()) {
          add(`${baseUrl}/best-of/${f}/`);
        }
      }
    }
  });

  // ═══ 9. COMPARE (town comparisons - lower priority) ═══
  collectUrls('compare', (add) => {
    const compareDir = path.join(outDir, 'compare');
    if (fs.existsSync(compareDir)) {
      for (const f of fs.readdirSync(compareDir)) {
        if (fs.statSync(path.join(compareDir, f)).isDirectory()) {
          add(`${baseUrl}/compare/${f}/`);
        }
      }
    }
  });

  // Write sitemap index
  writeSitemapIndex(outDir, sitemaps, today);

  // Summary
  console.log('Sitemaps generated:');
  let total = 0;
  for (const [name, count] of Object.entries(stats)) {
    console.log(`  sitemap-${name}.xml: ${count} URLs`);
    total += count;
  }
  console.log(`  sitemap.xml (index): ${sitemaps.length} sitemaps`);
  console.log(`Total: ${total} URLs`);
})();
